### ISSUE TITLE
error found in rust/diesel

### ISSUE THREAD

**Issue by ajaxdone** [YugaByte/orm-examples#39] opened 2019-06-30 10:17 UTC
After I tried to view from pgAdmin4, it shows this when try to view the data in users table:
```
ERROR:  Query error: Catalog Version Mismatch: A DDL occurred while processing this query. Try Again.
SQL state: XX000
```

Then try to cargo run again:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError(DatabaseError(__Unknown, "Query error: Catalog Version Mismatch: A DDL occurred while processing this query. Try Again."))', src/libcore/result.rs:999:5
```

**Comment by kmuthukk** [comment] 2019-06-30 14:41
hi @ajaxdone -- 

Thx for reporting.

`ERROR:  Query error: Catalog Version Mismatch: A DDL occurred while processing this query. Try Again.`

is a duplicate of https://github.com/YugaByte/yugabyte-db/issues/1457  that we are working on.

**Comment by srhickma** [comment] 2019-07-11 23:58
Hi @ajaxdone, YugaByte/yugabyte-db#1457 was fixed by commits https://github.com/YugaByte/yugabyte-db/commit/c7b3b0dae4e17ba56ea3a23e39fc21a474acdf3a and https://github.com/YugaByte/yugabyte-db/commit/ee336d6df61a09719d65d146ca0308b87865c9f4, so I will close this issue. Please re-open if your issue persists.

**Closed by srhickma** 2019-07-11 23:58 UTC
